/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhackALeakRouteImport } from './routes/whack-a-leak'
import { Route as SystemBreachRouteImport } from './routes/system-breach'
import { Route as StressTestRouteImport } from './routes/stress-test'
import { Route as SealDefenderRouteImport } from './routes/seal-defender'
import { Route as RogueAiRouteImport } from './routes/rogue-ai'
import { Route as OverrideRouteImport } from './routes/override'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as IntelligenceCheckRouteImport } from './routes/intelligence-check'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GitBlameRouteImport } from './routes/git-blame'
import { Route as Funny_url_listRouteImport } from './routes/funny_url_list'
import { Route as ForkliftSimRouteImport } from './routes/forklift-sim'
import { Route as FlappyPumpRouteImport } from './routes/flappy-pump'
import { Route as DoNotPushRouteImport } from './routes/do-not-push'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R418RouteImport } from './routes/418'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as AboutPaymentsRouteImport } from './routes/about_.payments'
import { Route as ProductsCategoryItemRouteImport } from './routes/products.$category_.$item'

const WhackALeakRoute = WhackALeakRouteImport.update({
  id: '/whack-a-leak',
  path: '/whack-a-leak',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemBreachRoute = SystemBreachRouteImport.update({
  id: '/system-breach',
  path: '/system-breach',
  getParentRoute: () => rootRouteImport,
} as any)
const StressTestRoute = StressTestRouteImport.update({
  id: '/stress-test',
  path: '/stress-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SealDefenderRoute = SealDefenderRouteImport.update({
  id: '/seal-defender',
  path: '/seal-defender',
  getParentRoute: () => rootRouteImport,
} as any)
const RogueAiRoute = RogueAiRouteImport.update({
  id: '/rogue-ai',
  path: '/rogue-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OverrideRoute = OverrideRouteImport.update({
  id: '/override',
  path: '/override',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceCheckRoute = IntelligenceCheckRouteImport.update({
  id: '/intelligence-check',
  path: '/intelligence-check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GitBlameRoute = GitBlameRouteImport.update({
  id: '/git-blame',
  path: '/git-blame',
  getParentRoute: () => rootRouteImport,
} as any)
const Funny_url_listRoute = Funny_url_listRouteImport.update({
  id: '/funny_url_list',
  path: '/funny_url_list',
  getParentRoute: () => rootRouteImport,
} as any)
const ForkliftSimRoute = ForkliftSimRouteImport.update({
  id: '/forklift-sim',
  path: '/forklift-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const FlappyPumpRoute = FlappyPumpRouteImport.update({
  id: '/flappy-pump',
  path: '/flappy-pump',
  getParentRoute: () => rootRouteImport,
} as any)
const DoNotPushRoute = DoNotPushRouteImport.update({
  id: '/do-not-push',
  path: '/do-not-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R418Route = R418RouteImport.update({
  id: '/418',
  path: '/418',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPaymentsRoute = AboutPaymentsRouteImport.update({
  id: '/about_/payments',
  path: '/about/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryItemRoute = ProductsCategoryItemRouteImport.update({
  id: '/products/$category_/$item',
  path: '/products/$category/$item',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/418': typeof R418Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/do-not-push': typeof DoNotPushRoute
  '/flappy-pump': typeof FlappyPumpRoute
  '/forklift-sim': typeof ForkliftSimRoute
  '/funny_url_list': typeof Funny_url_listRoute
  '/git-blame': typeof GitBlameRoute
  '/industries': typeof IndustriesRoute
  '/intelligence-check': typeof IntelligenceCheckRoute
  '/matrix': typeof MatrixRoute
  '/override': typeof OverrideRoute
  '/rogue-ai': typeof RogueAiRoute
  '/seal-defender': typeof SealDefenderRoute
  '/stress-test': typeof StressTestRoute
  '/system-breach': typeof SystemBreachRoute
  '/whack-a-leak': typeof WhackALeakRoute
  '/about/payments': typeof AboutPaymentsRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$category/$item': typeof ProductsCategoryItemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/418': typeof R418Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/do-not-push': typeof DoNotPushRoute
  '/flappy-pump': typeof FlappyPumpRoute
  '/forklift-sim': typeof ForkliftSimRoute
  '/funny_url_list': typeof Funny_url_listRoute
  '/git-blame': typeof GitBlameRoute
  '/industries': typeof IndustriesRoute
  '/intelligence-check': typeof IntelligenceCheckRoute
  '/matrix': typeof MatrixRoute
  '/override': typeof OverrideRoute
  '/rogue-ai': typeof RogueAiRoute
  '/seal-defender': typeof SealDefenderRoute
  '/stress-test': typeof StressTestRoute
  '/system-breach': typeof SystemBreachRoute
  '/whack-a-leak': typeof WhackALeakRoute
  '/about/payments': typeof AboutPaymentsRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products': typeof ProductsIndexRoute
  '/products/$category/$item': typeof ProductsCategoryItemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/418': typeof R418Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/do-not-push': typeof DoNotPushRoute
  '/flappy-pump': typeof FlappyPumpRoute
  '/forklift-sim': typeof ForkliftSimRoute
  '/funny_url_list': typeof Funny_url_listRoute
  '/git-blame': typeof GitBlameRoute
  '/industries': typeof IndustriesRoute
  '/intelligence-check': typeof IntelligenceCheckRoute
  '/matrix': typeof MatrixRoute
  '/override': typeof OverrideRoute
  '/rogue-ai': typeof RogueAiRoute
  '/seal-defender': typeof SealDefenderRoute
  '/stress-test': typeof StressTestRoute
  '/system-breach': typeof SystemBreachRoute
  '/whack-a-leak': typeof WhackALeakRoute
  '/about_/payments': typeof AboutPaymentsRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$category_/$item': typeof ProductsCategoryItemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/418'
    | '/about'
    | '/contact'
    | '/do-not-push'
    | '/flappy-pump'
    | '/forklift-sim'
    | '/funny_url_list'
    | '/git-blame'
    | '/industries'
    | '/intelligence-check'
    | '/matrix'
    | '/override'
    | '/rogue-ai'
    | '/seal-defender'
    | '/stress-test'
    | '/system-breach'
    | '/whack-a-leak'
    | '/about/payments'
    | '/products/$category'
    | '/products/'
    | '/products/$category/$item'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/418'
    | '/about'
    | '/contact'
    | '/do-not-push'
    | '/flappy-pump'
    | '/forklift-sim'
    | '/funny_url_list'
    | '/git-blame'
    | '/industries'
    | '/intelligence-check'
    | '/matrix'
    | '/override'
    | '/rogue-ai'
    | '/seal-defender'
    | '/stress-test'
    | '/system-breach'
    | '/whack-a-leak'
    | '/about/payments'
    | '/products/$category'
    | '/products'
    | '/products/$category/$item'
  id:
    | '__root__'
    | '/'
    | '/418'
    | '/about'
    | '/contact'
    | '/do-not-push'
    | '/flappy-pump'
    | '/forklift-sim'
    | '/funny_url_list'
    | '/git-blame'
    | '/industries'
    | '/intelligence-check'
    | '/matrix'
    | '/override'
    | '/rogue-ai'
    | '/seal-defender'
    | '/stress-test'
    | '/system-breach'
    | '/whack-a-leak'
    | '/about_/payments'
    | '/products/$category'
    | '/products/'
    | '/products/$category_/$item'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R418Route: typeof R418Route
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DoNotPushRoute: typeof DoNotPushRoute
  FlappyPumpRoute: typeof FlappyPumpRoute
  ForkliftSimRoute: typeof ForkliftSimRoute
  Funny_url_listRoute: typeof Funny_url_listRoute
  GitBlameRoute: typeof GitBlameRoute
  IndustriesRoute: typeof IndustriesRoute
  IntelligenceCheckRoute: typeof IntelligenceCheckRoute
  MatrixRoute: typeof MatrixRoute
  OverrideRoute: typeof OverrideRoute
  RogueAiRoute: typeof RogueAiRoute
  SealDefenderRoute: typeof SealDefenderRoute
  StressTestRoute: typeof StressTestRoute
  SystemBreachRoute: typeof SystemBreachRoute
  WhackALeakRoute: typeof WhackALeakRoute
  AboutPaymentsRoute: typeof AboutPaymentsRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCategoryItemRoute: typeof ProductsCategoryItemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whack-a-leak': {
      id: '/whack-a-leak'
      path: '/whack-a-leak'
      fullPath: '/whack-a-leak'
      preLoaderRoute: typeof WhackALeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-breach': {
      id: '/system-breach'
      path: '/system-breach'
      fullPath: '/system-breach'
      preLoaderRoute: typeof SystemBreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress-test': {
      id: '/stress-test'
      path: '/stress-test'
      fullPath: '/stress-test'
      preLoaderRoute: typeof StressTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seal-defender': {
      id: '/seal-defender'
      path: '/seal-defender'
      fullPath: '/seal-defender'
      preLoaderRoute: typeof SealDefenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rogue-ai': {
      id: '/rogue-ai'
      path: '/rogue-ai'
      fullPath: '/rogue-ai'
      preLoaderRoute: typeof RogueAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/override': {
      id: '/override'
      path: '/override'
      fullPath: '/override'
      preLoaderRoute: typeof OverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence-check': {
      id: '/intelligence-check'
      path: '/intelligence-check'
      fullPath: '/intelligence-check'
      preLoaderRoute: typeof IntelligenceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-blame': {
      id: '/git-blame'
      path: '/git-blame'
      fullPath: '/git-blame'
      preLoaderRoute: typeof GitBlameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funny_url_list': {
      id: '/funny_url_list'
      path: '/funny_url_list'
      fullPath: '/funny_url_list'
      preLoaderRoute: typeof Funny_url_listRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forklift-sim': {
      id: '/forklift-sim'
      path: '/forklift-sim'
      fullPath: '/forklift-sim'
      preLoaderRoute: typeof ForkliftSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flappy-pump': {
      id: '/flappy-pump'
      path: '/flappy-pump'
      fullPath: '/flappy-pump'
      preLoaderRoute: typeof FlappyPumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-not-push': {
      id: '/do-not-push'
      path: '/do-not-push'
      fullPath: '/do-not-push'
      preLoaderRoute: typeof DoNotPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/418': {
      id: '/418'
      path: '/418'
      fullPath: '/418'
      preLoaderRoute: typeof R418RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/payments': {
      id: '/about_/payments'
      path: '/about/payments'
      fullPath: '/about/payments'
      preLoaderRoute: typeof AboutPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category_/$item': {
      id: '/products/$category_/$item'
      path: '/products/$category/$item'
      fullPath: '/products/$category/$item'
      preLoaderRoute: typeof ProductsCategoryItemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R418Route: R418Route,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DoNotPushRoute: DoNotPushRoute,
  FlappyPumpRoute: FlappyPumpRoute,
  ForkliftSimRoute: ForkliftSimRoute,
  Funny_url_listRoute: Funny_url_listRoute,
  GitBlameRoute: GitBlameRoute,
  IndustriesRoute: IndustriesRoute,
  IntelligenceCheckRoute: IntelligenceCheckRoute,
  MatrixRoute: MatrixRoute,
  OverrideRoute: OverrideRoute,
  RogueAiRoute: RogueAiRoute,
  SealDefenderRoute: SealDefenderRoute,
  StressTestRoute: StressTestRoute,
  SystemBreachRoute: SystemBreachRoute,
  WhackALeakRoute: WhackALeakRoute,
  AboutPaymentsRoute: AboutPaymentsRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCategoryItemRoute: ProductsCategoryItemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
